#!/usr/bin/env bash
#Write a Bash script that displays all active
# IPv4 IPs on the machine it’s executed on.

# Use the 'ip' command to extract active IPv4 addresses
ip -4 -o addr show | awk '{print $4}' | cut -d'/' -f1
