#!/usr/bin/env bash
#Write a Bash script that displays all active
# IPv4 IPs on the machine it’s executed on.

# Use the 'ip' command to extract active IPv4 addresses
ifconfig | grep -w "inet" | awk '{print $2}'
